// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DOMAIN.Apae_Administrativo_Excepcionais.Entities
{
    public partial class TbFuncionario
    {
        public int CdFuncionario { get; set; }
        public int CdPessoa { get; set; }
        public string NmLogin { get; set; }
        public string NmSenha { get; set; }
        public int CdTipoFuncionario { get; set; }

        public virtual TbPessoa CdPessoaNavigation { get; set; }
        public virtual TbTipoFuncionario CdTipoFuncionarioNavigation { get; set; }
    }
}