// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DOMAIN.Apae_Administrativo_Excepcionais.Entities
{
    public partial class TbTipoFuncionario
    {
        public TbTipoFuncionario()
        {
            TbFuncionario = new HashSet<TbFuncionario>();
        }

        public int CdTipoFuncionario { get; set; }
        public string DsTipoFuncionario { get; set; }

        public virtual ICollection<TbFuncionario> TbFuncionario { get; set; }
    }
}