// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


using DOMAIN.Apae_Administrativo_Excepcionais.Entities;
using Microsoft.EntityFrameworkCore;

namespace DOMAIN.Apae_Administrativo_Excepcionais
{
    public partial class Context : DbContext
    {
        public Context()
        {
        }

        public Context(DbContextOptions<Context> options)
            : base(options)
        {
        }

        public virtual DbSet<TbFuncionario> TbFuncionario { get; set; }
        public virtual DbSet<TbPessoa> TbPessoa { get; set; }
        public virtual DbSet<TbTipoFuncionario> TbTipoFuncionario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TbFuncionario>(entity =>
            {
                entity.HasKey(e => e.CdFuncionario)
                    .HasName("PK__TB_FUNCI__2B77185AD4A5340C");

                entity.ToTable("TB_FUNCIONARIO");

                entity.Property(e => e.CdFuncionario)
                    .HasColumnName("CD_FUNCIONARIO")
                    .ValueGeneratedNever();

                entity.Property(e => e.CdPessoa).HasColumnName("CD_PESSOA");

                entity.Property(e => e.CdTipoFuncionario).HasColumnName("CD_TIPO_FUNCIONARIO");

                entity.Property(e => e.NmLogin)
                    .HasColumnName("NM_LOGIN")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NmSenha)
                    .HasColumnName("NM_SENHA")
                    .HasMaxLength(12)
                    .IsUnicode(false);

                entity.HasOne(d => d.CdPessoaNavigation)
                    .WithMany(p => p.TbFuncionario)
                    .HasForeignKey(d => d.CdPessoa)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_PesFuncionario");

                entity.HasOne(d => d.CdTipoFuncionarioNavigation)
                    .WithMany(p => p.TbFuncionario)
                    .HasForeignKey(d => d.CdTipoFuncionario)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_TipoFuncFuncionario");
            });

            modelBuilder.Entity<TbPessoa>(entity =>
            {
                entity.HasKey(e => e.CdPessoa)
                    .HasName("PK__TB_PESSO__2CBD72279ED086AF");

                entity.ToTable("TB_PESSOA");

                entity.Property(e => e.CdPessoa)
                    .HasColumnName("CD_PESSOA")
                    .ValueGeneratedNever();

                entity.Property(e => e.NmNomeCompleto)
                    .HasColumnName("NM_NOME_COMPLETO")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NmTelefone)
                    .HasColumnName("NM_TELEFONE")
                    .HasMaxLength(12)
                    .IsUnicode(false);

                entity.Property(e => e.NrCpf)
                    .HasColumnName("NR_CPF")
                    .HasColumnType("numeric(14, 0)");
            });

            modelBuilder.Entity<TbTipoFuncionario>(entity =>
            {
                entity.HasKey(e => e.CdTipoFuncionario)
                    .HasName("PK__TB_TIPO___A8EB2EFD0B12B4DC");

                entity.ToTable("TB_TIPO_FUNCIONARIO");

                entity.Property(e => e.CdTipoFuncionario)
                    .HasColumnName("CD_TIPO_FUNCIONARIO")
                    .ValueGeneratedNever();

                entity.Property(e => e.DsTipoFuncionario)
                    .HasColumnName("DS_TIPO_FUNCIONARIO")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}